"""User update v2

Revision ID: 851f86176609
Revises: a808552df900
Create Date: 2025-08-04 13:26:23.209101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851f86176609'
down_revision: Union[str, Sequence[str], None] = 'a808552df900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=1)
    # ### end Alembic commands ###
